[package]
name = "watcher-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
bpfx = {path = "/home/vamsi/scripts/bpfx/", features = ["archive"]}
chrono = "0.4.44"
clap = { version = "4.6.5", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = { version = "0.29.0"}
directories = "6.0.0"
env_logger = "0.11.11"
futures = "0.3.33"
libc = "0.2.186"
lru = "0.18.1"
nix = { version = "0.31.3", features = ["time"] }
ratatui = "0.30.0"
rkyv = "0.8.16"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "1.1.4"
tracing = "0.1.44"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
