[package]
name = "watcher-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
aya = "0.13.1"
aya-ebpf = "0.1.1"
aya-ebpf-macros = "0.1.2"
aya-log = "0.2.1"
aya-log-ebpf = "0.1.0"
chrono = "0.4.44"
env_logger = "0.11.10"
libc = "0.2.186"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
watcher-rs-common = {path = "./watcher-rs-common/"}
